"""Layout comparison CLI commands."""

from pathlib import Path
from typing import Annotated, Any

import typer

from glovebox.cli.commands.layout.base import LayoutOutputCommand
from glovebox.cli.decorators import handle_errors
from glovebox.cli.helpers.parameters import OutputFormatOption, ProfileOption
from glovebox.layout.comparison import create_layout_comparison_service


@handle_errors
def diff(
    layout1: Annotated[Path, typer.Argument(help="First layout file to compare")],
    layout2: Annotated[Path, typer.Argument(help="Second layout file to compare")],
    output_format: Annotated[
        str,
        typer.Option(
            "--output-format",
            help="Output format: summary (default), detailed, dtsi, or json",
        ),
    ] = "summary",
    compare_dtsi: Annotated[
        bool,
        typer.Option(
            "--compare-dtsi", help="Include detailed custom DTSI code comparison"
        ),
    ] = False,
) -> None:
    """Compare two layouts showing differences.

    Shows differences between two layout files, focusing on layers,
    behaviors, custom DTSI code, and configuration changes.

    Output Formats:
        summary  - Basic difference counts (default)
        detailed - Individual key differences within layers
        dtsi     - Detailed DTSI code differences with unified diff
        json     - Structured data with exact key changes for automation

    The --compare-dtsi flag enables detailed custom DTSI code comparison
    for any output format.

    Examples:
        # Basic comparison showing layer and config changes
        glovebox layout diff my-layout-v41.json my-layout-v42.json

        # Detailed view with individual key differences
        glovebox layout diff layout1.json layout2.json --output-format detailed

        # Include custom DTSI code differences
        glovebox layout diff layout1.json layout2.json --compare-dtsi

        # DTSI-focused output with unified diff format
        glovebox layout diff layout1.json layout2.json --output-format dtsi

        # JSON output with structured key change data
        glovebox layout diff layout1.json layout2.json --output-format json

        # JSON with DTSI differences for complete automation
        glovebox layout diff layout1.json layout2.json --output-format json --compare-dtsi

        # Extract single-line patch string for merge tools
        glovebox layout diff layout1.json layout2.json --output-format json --compare-dtsi | jq -r '.custom_dtsi.custom_defined_behaviors.patch_string'

        # Compare your custom layout with a master version
        glovebox layout diff ~/.glovebox/masters/glove80/v42-rc3.json my-custom.json --output-format detailed

        # Process JSON output with jq to extract specific changes
        glovebox layout diff layout1.json layout2.json --output-format json | jq '.layers.changed.Cursor.key_changes'
    """
    command = LayoutOutputCommand()
    command.validate_layout_file(layout1)
    command.validate_layout_file(layout2)

    try:
        comparison_service = create_layout_comparison_service()
        result = comparison_service.compare_layouts(
            layout1_path=layout1,
            layout2_path=layout2,
            output_format=output_format,
            compare_dtsi=compare_dtsi,
        )

        if output_format.lower() == "json":
            command.format_output(result, "json")
        else:
            # Generate text output from comparison result
            differences = _format_comparison_text(result, output_format, compare_dtsi)
            if not differences:
                from glovebox.cli.helpers import print_success_message

                print_success_message("No significant differences found")
            else:
                from glovebox.cli.helpers import print_list_item, print_success_message

                print_success_message(f"Found {len(differences)} difference(s):")
                for diff in differences:
                    print_list_item(diff)

    except Exception as e:
        command.handle_service_error(e, "compare layouts")


@handle_errors
def patch(
    source_layout: Annotated[Path, typer.Argument(help="Source layout file to patch")],
    patch_file: Annotated[
        Path,
        typer.Argument(
            help="JSON diff file from 'glovebox layout diff --output-format json'"
        ),
    ],
    output: Annotated[
        Path | None,
        typer.Option(
            "--output",
            "-o",
            help="Output path (default: source_layout with -patched suffix)",
        ),
    ] = None,
    force: Annotated[
        bool, typer.Option("--force", help="Overwrite existing files")
    ] = False,
) -> None:
    """Apply a JSON diff patch to transform a layout.

    Takes a source layout and applies changes from a JSON diff file
    (generated by 'glovebox layout diff --output-format json') to create
    a new transformed layout.

    Examples:
        # Generate a diff
        glovebox layout diff old.json new.json --output-format json > changes.json

        # Apply the diff to transform another layout
        glovebox layout patch my-layout.json changes.json --output patched-layout.json

        # Apply diff with auto-generated output name
        glovebox layout patch my-layout.json changes.json
    """
    command = LayoutOutputCommand()
    command.validate_layout_file(source_layout)

    try:
        comparison_service = create_layout_comparison_service()
        result = comparison_service.apply_patch(
            source_layout_path=source_layout,
            patch_file_path=patch_file,
            output=output,
            force=force,
        )

        # Show success with details
        command.print_operation_success(
            "Applied patch successfully",
            {
                "source": result["source"],
                "patch": result["patch"],
                "output": result["output"],
                "applied_changes": result["total_changes"],
            },
        )

    except Exception as e:
        command.handle_service_error(e, "apply patch")


@handle_errors
def create_patch(
    layout1: Annotated[Path, typer.Argument(help="Original layout file")],
    layout2: Annotated[Path, typer.Argument(help="Modified layout file")],
    output: Annotated[
        Path | None,
        typer.Option(
            "--output", "-o", help="Output patch file (default: auto-generated)"
        ),
    ] = None,
    section: Annotated[
        str,
        typer.Option(
            "--section", help="DTSI section to patch: behaviors, devicetree, or both"
        ),
    ] = "both",
) -> None:
    """Create a unified diff patch file for custom DTSI sections.

    Generates standard unified diff patches that can be used with merge tools
    like git apply, patch command, or merge tools.

    The patch focuses on custom_defined_behaviors and custom_devicetree
    sections only, providing merge-tool compatible output.

    Examples:
        # Create patch for both DTSI sections
        glovebox layout create-patch old.json new.json --output changes.patch

        # Create patch for behaviors only
        glovebox layout create-patch old.json new.json --section behaviors

        # Create patch for devicetree only
        glovebox layout create-patch old.json new.json --section devicetree

        # Auto-generate patch filename
        glovebox layout create-patch old.json new.json
    """
    command = LayoutOutputCommand()
    command.validate_layout_file(layout1)
    command.validate_layout_file(layout2)

    try:
        comparison_service = create_layout_comparison_service()
        result = comparison_service.create_dtsi_patch(
            layout1_path=layout1,
            layout2_path=layout2,
            output=output,
            section=section,
        )

        if not result["has_differences"]:
            from glovebox.cli.helpers import print_success_message

            print_success_message("No differences found in specified DTSI sections")
            return

        # Show success with details
        command.print_operation_success(
            "Created patch file successfully",
            {
                "source": result["source"],
                "target": result["target"],
                "output": result["output"],
                "sections": result["sections"],
                "patch_size": f"{result['patch_lines']} lines",
            },
        )

        # Show usage instructions
        from glovebox.cli.helpers import print_list_item, print_success_message

        print_success_message("Usage instructions:")
        print_list_item(f"Apply with git: git apply {result['output']}")
        print_list_item(f"Apply with patch: patch -p1 < {result['output']}")
        print_list_item(f"View with diff tool: your-merge-tool {result['output']}")

    except Exception as e:
        command.handle_service_error(e, "create patch")


def _format_comparison_text(
    result: dict[str, Any], output_format: str, compare_dtsi: bool
) -> list[str]:
    """Format comparison result for text output."""
    differences = []

    # Add metadata changes
    for field, change in result.get("metadata", {}).items():
        if isinstance(change, dict) and "from" in change and "to" in change:
            differences.append(
                f"{field.title()}: '{change['from']}' → '{change['to']}'"
            )

    # Add layer changes
    layers = result.get("layers", {})
    if layers.get("added"):
        differences.append(f"Added layers: {', '.join(sorted(layers['added']))}")
    if layers.get("removed"):
        differences.append(f"Removed layers: {', '.join(sorted(layers['removed']))}")

    # Add layer key changes for detailed output
    if output_format.lower() == "detailed":
        for layer_name, layer_changes in layers.get("changed", {}).items():
            key_count = layer_changes.get("total_key_differences", 0)
            differences.append(f"Layer '{layer_name}': {key_count} key differences")

            # Show individual key changes (limited)
            for key_change in layer_changes.get("key_changes", [])[:5]:
                key_idx = key_change.get("key_index")
                from_val = key_change.get("from", "None")
                to_val = key_change.get("to", "None")
                # Truncate long values
                from_str = (
                    from_val[:40] + "..." if len(str(from_val)) > 40 else str(from_val)
                )
                to_str = to_val[:40] + "..." if len(str(to_val)) > 40 else str(to_val)
                differences.append(f"  Key {key_idx:2d}: '{from_str}' → '{to_str}'")

            # Show truncation if needed
            total_changes = len(layer_changes.get("key_changes", []))
            if total_changes > 5:
                differences.append(f"  ... and {total_changes - 5} more changes")

    # Add behavior changes
    behaviors = result.get("behaviors", {})
    if behaviors.get("changed"):
        count1 = behaviors.get("layout1_count", 0)
        count2 = behaviors.get("layout2_count", 0)
        differences.append(f"Behaviors: {count1} → {count2}")

    # Add config changes
    config = result.get("config", {})
    if config.get("changed"):
        count1 = config.get("layout1_count", 0)
        count2 = config.get("layout2_count", 0)
        differences.append(f"Config parameters: {count1} → {count2}")

    # Add DTSI changes
    dtsi = result.get("custom_dtsi", {})
    if dtsi.get("custom_defined_behaviors", {}).get("changed"):
        differences.append("custom_defined_behaviors: Content differs")
    if dtsi.get("custom_devicetree", {}).get("changed"):
        differences.append("custom_devicetree: Content differs")

    return differences
